image: python:3.6-jessie
build:
  tags:
    - docker
  script:
    - apt-get update && apt-get install python-numpy
    - pip install --upgrade Cython
    - pip install --upgrade numpy
    - pip install --upgrade pip setuptools wheel
    - pip install '.'
